spring.cloud.stream.bindings.process-in-0:
  destination: play-events
spring.cloud.stream.bindings.process-in-1:
  destination: song-feed
spring.cloud.stream.kafka.streams.bindings.process-in-0:
  consumer:
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
spring.cloud.stream.kafka.streams.bindings.process-in-1:
  consumer:
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    materializedAs: all-songs
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  configuration:
    schema.registry.url: http://localhost:8081
    commit.interval.ms: 1000
    num.standby.replicas: 0
spring.cloud.stream.kafka.streams.binder.autoAddPartitions: true
spring.cloud.stream.kafka.streams.binder.minPartitionCount: 4
spring.cloud.stream.kafka.streams.binder.configuration.application.server: localhost:8080

spring.application.name: kafka-streams-iq-advanced-sample